import {Office,avatarSymbol} from './office.js';
const $=s=>document.querySelector(s),create=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
let live={sessions:[],events:[]},demo=new URLSearchParams(location.search).get('demo')==='1',online=false,selected=null,stream,simulated,simEvents=[],demoTimer;
const labels={WORKING:'Bekerja',IDLE:'Istirahat',WAITING_APPROVAL:'Approval',WAITING_USER:'Menunggu',CRASHED:'Terhenti',EXITED:'Selesai sesi',UNKNOWN:'Belum diketahui'};
const colors=['#927bb7','#7f9e8e','#bf9b6d','#7e9ab8'];
const office=new Office($('#office'),openDetail);const reduced=matchMedia('(prefers-reduced-motion: reduce)');$('#economy').checked=localStorage.getItem('office-economy')==='true'||reduced.matches;office.setLow($('#economy').checked);
function sample(){const now=Date.now();simulated=[{id:'demo-nara',agent_id:'demo-nara',name:'Nara',role:'SEO specialist',task:'Artikel: jajanan untuk wedding',project:'Teman Nikah',runtime:'WORKING',character:'human'},{id:'demo-arka',agent_id:'demo-arka',name:'Arka',role:'Developer',task:'Rapikan tampilan kasir',project:'Leker',runtime:'WORKING',character:'robot'},{id:'demo-milo',agent_id:'demo-milo',name:'Milo',role:'Content writer',task:'Menunggu tugas berikutnya',project:'MAXI',runtime:'IDLE',character:'cat'},{id:'demo-lumi',agent_id:'demo-lumi',name:'Lumi',role:'Quality assurance',task:'Review hasil pengujian',project:'Leker',runtime:'WAITING_APPROVAL',character:'bunny'}].map((s,i)=>({...s,color:colors[i],harness:'Claude Code',provider:'Contoh provider',model:'Contoh model',telemetry:'CONNECTED',evidence:'SIMULATED',source:'demo',last_seen:now,last_activity:now,activity:labels[s.runtime],task_status:'IN_PROGRESS'}));simEvents=simulated.map((s,i)=>({id:String(i),session_id:s.id,name:s.name,type:i===2?'turn_end':i===3?'waiting_approval':'tool_start',tool:i===0?'Edit artikel':i===1?'Jalankan tes':'',received_at:now-i*16000,evidence:'SIMULATED'}));}
sample();
function sessions(){return demo?simulated:live.sessions;}function ago(t){const sec=Math.max(0,Math.floor((Date.now()-t)/1000));return sec<60?`${sec}d lalu`:sec<3600?`${Math.floor(sec/60)}m lalu`:`${Math.floor(sec/3600)}j lalu`;}
function stale(s){return !demo&&(!online||Date.now()-s.last_seen>90000)||['STALE','DISCONNECTED'].includes(s.telemetry);}
function render(){const rows=sessions(),q=$('#search').value.toLowerCase();$('#total').textContent=rows.length;$('#working').textContent=rows.filter(s=>s.runtime==='WORKING'&&!stale(s)).length;$('#attention').textContent=rows.filter(s=>stale(s)||s.warning||['WAITING_APPROVAL','WAITING_USER','CRASHED'].includes(s.runtime)).length;$('#team-count').textContent=rows.length;$('#empty').hidden=rows.length>0;$('#mode-label').textContent=demo?'DEMO / SIMULASI':'LIVE';$('#demo-controls').hidden=!demo;$('#demo-toggle').textContent=demo?'Kembali ke live ↗':'Coba demo ↗';$('#connection').textContent=demo?'Mode demo · simulasi':online?(live.cloud?'Cloud terhubung':'Collector terhubung'):'Live belum terhubung';$('#connection-dot').style.background=demo?'#ac91c3':online?'#86ab96':'#c9ac79';$('#local-coverage').textContent=demo?'Data simulasi':rows.length?'Event diterima':'Belum ada event';$('#evidence-note').textContent=demo?'SIMULASI • bukan aktivitas agent asli':'Bukti event • metadata saja';const target=$('#agents');target.replaceChildren();for(const [i,s]of rows.filter(s=>[s.name,s.role,s.task].join(' ').toLowerCase().includes(q)).entries()){
 const button=create('button','agent-card');button.dataset.session=s.id;const avatar=create('div','avatar',avatarSymbol(s.character));avatar.style.background=(s.color||colors[i%4])+'20';avatar.style.color=s.color||colors[i%4];button.append(avatar);const info=create('div'),name=create('div','agent-name',s.name||'Agent baru'),state=create('small','',stale(s)?'Data terputus':labels[s.runtime]||s.runtime);state.style.color=stale(s)?'#9995a2':s.runtime.startsWith('WAITING')?'#bd995d':s.runtime==='WORKING'?'#83a18c':'#a28bbd';name.append(state);info.append(name,create('div','agent-role',`${s.role||'Belum diatur'} · ${s.project||'Workspace'}`),create('div','agent-task',s.task||s.activity||'Belum ada task terkait'),create('div','agent-proof',`${s.evidence||'UNKNOWN'} · ${ago(s.last_seen)}${s.telemetry==='EVENTS_ONLY'?' · event saja':''}`));button.append(info);button.onclick=()=>openDetail(s.id);target.append(button);}
 if(!target.children.length)target.append(create('div','empty-list',q?'Tidak ada agent yang cocok.':'Belum ada sesi. Buka launcher lokal untuk menghubungkan kantor, lalu jalankan agent.'));office.setSessions(rows,demo||online);
 const timeline=$('#timeline');timeline.replaceChildren();const events=(demo?simEvents:live.events).filter(e=>e.type!=='process_heartbeat').slice(0,5);for(const e of events){const item=create('article','event'),time=create('time','',new Date(e.received_at).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'}));item.append(time,create('strong','',e.name||'Agent'),create('p','',eventLabel(e)),create('small','',e.evidence||'OBSERVED'));timeline.append(item);}if(!events.length)timeline.append(create('p','empty-list','Belum ada event. Status tidak akan ditebak.'));
}
function eventLabel(e){return {session_start:'Sesi baru masuk',process_start:'Proses dimulai',tool_start:`Memulai ${e.tool||'tool'}`,tool_end:'Tool selesai',tool_error:'Tool gagal',waiting_approval:'Meminta persetujuan',waiting_user:'Menunggu jawaban',turn_end:'Giliran selesai · istirahat',session_end:'Sesi berakhir',process_exit:'Proses keluar',task_written:'Berhasil menulis task',work_start:'Mulai mengerjakan tugas',task_report:'Laporan task diterima'}[e.type]||e.type;}
function openDetail(id){selected=id;const s=sessions().find(s=>s.id===id);if(!s)return;$('#detail-title').textContent=s.name;const info=$('#detail-info');info.replaceChildren();for(const [label,value]of [['Status',stale(s)?'Data terputus':labels[s.runtime]],['Tugas',s.task||'Belum dikaitkan'],['Sumber tugas',s.task_source==='LAUNCHER_METADATA'?'Metadata launcher · dilaporkan':demo?'SIMULASI':'Belum tersedia'],['Sumber',`${s.source||'—'} · ${s.evidence}`],['Mesin',s.harness||'Belum diketahui'],['Provider/model terkonfigurasi',[s.provider,s.model].filter(Boolean).join(' / ')||'Tidak tersedia'],['Koneksi telemetry',s.telemetry],['Aktivitas terakhir',s.activity||'—'],['File',s.file||'Tidak tersedia'],['Status task',s.task_status||'UNKNOWN'],['Sesi',s.id]]){const row=create('div','detail-row');row.append(create('span','',label),create('b','',value));info.append(row);}const form=$('#profile-form');for(const k of ['name','role','character','color'])form.elements[k].value=s[k]||({character:'human',color:'#927bb7'}[k]||'');$('#profile-status').textContent=demo?'Pengaturan ini hanya untuk karakter demo.':live.cloud?'Edit tampilan melalui kantor lokal, lalu sinkronkan.':'Disimpan lokal untuk identitas agent ini.';if(!$('#detail').open)$('#detail').showModal();}
$('#profile-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(demo){Object.assign(simulated.find(s=>s.id===selected),data);render();$('#profile-status').textContent='Tampilan demo disimpan.';return;}if(live.cloud){$('#profile-status').textContent='Edit tampilan melalui kantor lokal.';return;}try{const r=await fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...data,session_id:selected})});if(!r.ok)throw Error();$('#profile-status').textContent='Tampilan tersimpan.';}catch{$('#profile-status').textContent='Gagal menyimpan. Cek koneksi collector.';}};
$('#search').oninput=render;$('#show-team').onclick=()=>$('#team-panel').scrollIntoView({behavior:$('#economy').checked?'instant':'smooth'});$('#economy').onchange=e=>{localStorage.setItem('office-economy',e.target.checked);office.setLow(e.target.checked);};
$('#demo-toggle').onclick=()=>{demo=!demo;const url=new URL(location);if(demo)url.searchParams.set('demo','1');else url.searchParams.delete('demo');history.replaceState(null,'',url);render();};
for(const b of document.querySelectorAll('[data-demo]'))b.onclick=()=>{clearTimeout(demoTimer);const s=simulated[0],state=b.dataset.demo;s.runtime=state==='BOARD'?'WORKING':state==='DISCONNECTED'?'WORKING':state;s.telemetry=state==='DISCONNECTED'?'DISCONNECTED':'CONNECTED';s.last_seen=Date.now();s.board_until=state==='BOARD'?Date.now()+6000:0;s.activity=state==='BOARD'?'Task berhasil ditulis':labels[s.runtime];simEvents.unshift({id:String(Date.now()),session_id:s.id,name:s.name,type:state==='BOARD'?'task_written':state==='IDLE'?'turn_end':state==='WAITING_APPROVAL'?'waiting_approval':state==='DISCONNECTED'?'Data terputus':'work_start',received_at:Date.now(),evidence:'SIMULATED'});simEvents=simEvents.slice(0,30);render();if(state==='BOARD')demoTimer=setTimeout(()=>{s.board_until=0;render();},6000);};
async function connect(){try{const fragment=new URLSearchParams(location.hash.slice(1)),token=fragment.get('access');if(token){history.replaceState(null,'',location.pathname+location.search);await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});}const r=await fetch('/api/snapshot');if(!r.ok){online=false;render();return;}live=await r.json();online=true;stream=live.cloud?new WebSocket(location.origin.replace('https:','wss:')+'/api/ws'):new EventSource('/api/stream');stream.onmessage=e=>{live=JSON.parse(e.data);online=true;render();};stream.onerror=()=>{online=false;render();};if(live.cloud){stream.onclose=()=>{online=false;render();setTimeout(connect,5000);};stream.onopen=()=>{online=true;render();};}render();}catch{online=false;render();}}
function clock(){$('#clock').textContent=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'})+' WIB';}clock();setInterval(()=>{clock();if(!document.hidden)render();},15000);render();connect();
