import STATIC from './static.mjs';
import {presentSession,cleanEvent} from '../lib/model.mjs';
const headers={'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"};
const json=(v,status=200,extra={})=>new Response(JSON.stringify(v),{status,headers:{...headers,'content-type':'application/json',...extra}});
export function sanitizeSnapshot(input,now=Date.now()){
 if(!input||!Array.isArray(input.sessions)||!Array.isArray(input.events)||input.sessions.length>200)throw Error('Invalid snapshot');
 const fields=['id','agent_id','name','role','project','branch','task','task_id','tool','file','harness','provider','model','runtime','task_status','activity','source','evidence','task_source','character','color','office_action'];
 const times=['started_at','last_seen','last_activity','last_order','last_process','last_hook','board_until','claim_until'];
 const sessions=input.sessions.map(s=>{const out={};for(const k of fields)if(typeof s[k]==='string')out[k]=s[k].replace(/[\u0000-\u001f]/g,' ').slice(0,240);if(!/^[\w.:/-]{1,160}$/.test(out.id||'')||!/^[\w.:/-]{1,160}$/.test(out.agent_id||''))throw Error('Invalid session');for(const k of times)if(Number.isFinite(s[k]))out[k]=Math.min(now+5000,Math.max(now-7*86400000,s[k]));out.process_observed=s.process_observed===true;out.restored=s.restored===true;return out;});
 const events=input.events.slice(0,60).map(e=>({...cleanEvent(e,Number.isFinite(e.received_at)?Math.min(now,e.received_at):now),name:typeof e.name==='string'?e.name.slice(0,100):''}));
 return {sessions,events};
}
export class OfficeRoom {
 constructor(ctx,env){this.ctx=ctx;this.env=env;ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping','pong'));}
 async snapshot(){const now=Date.now(),rows=await this.env.DB.prepare('SELECT device,received,data FROM device_snapshots WHERE received>? ORDER BY received DESC LIMIT 5').bind(now-7*86400000).all();const sessions=[],events=[];for(const row of rows.results){const s=JSON.parse(row.data);for(const item of s.sessions){const fresh=presentSession(item,now);sessions.push({...fresh,id:row.device+':'+item.id,agent_id:row.device+':'+item.agent_id,telemetry:now-row.received>90000?'DISCONNECTED':fresh.telemetry});}for(const e of s.events)events.push({...e,id:row.device+':'+e.id,session_id:row.device+':'+e.session_id});}return {at:now,sessions:sessions.slice(0,200),events:events.sort((a,b)=>b.received_at-a.received_at).slice(0,60),cloud:true,coverage:{cloud:'Cloudflare + D1',board:'Belum terhubung'},llm_calls:0};}
 async fetch(request){const path=new URL(request.url).pathname;if(path==='/api/sync')return this.ctx.blockConcurrencyWhile(async()=>{const text=await request.text();if(text.length>262144)return json({error:'Payload too large'},413);let b;try{b=JSON.parse(text);if(!/^[a-zA-Z0-9_-]{1,40}$/.test(b.device))throw Error();b.snapshot=sanitizeSnapshot(b.snapshot);}catch{return json({error:'Invalid snapshot'},400);}const existing=await this.env.DB.prepare('SELECT COUNT(*) AS n FROM device_snapshots WHERE device!=?').bind(b.device).first();if(existing.n>=5)return json({error:'Device limit'},429);const now=Date.now();await this.env.DB.prepare('INSERT INTO device_snapshots(device,received,data) VALUES(?,?,?) ON CONFLICT(device) DO UPDATE SET received=excluded.received,data=excluded.data').bind(b.device,now,JSON.stringify(b.snapshot)).run();const payload=JSON.stringify(await this.snapshot());for(const ws of this.ctx.getWebSockets()){try{ws.send(payload);}catch{ws.close(1011,'Reconnect');}}return json({ok:true});});
 if(path==='/api/ws'){if(request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return json({error:'Upgrade required'},426);if(this.ctx.getWebSockets().length>=20)return json({error:'Viewer limit'},429);const [client,server]=Object.values(new WebSocketPair());this.ctx.acceptWebSocket(server);server.send(JSON.stringify(await this.snapshot()));return new Response(null,{status:101,webSocket:client});}return json(await this.snapshot());}
 webSocketMessage(ws,message){if(message==='refresh')this.snapshot().then(s=>ws.send(JSON.stringify(s))).catch(()=>ws.close(1011,'Reconnect'));}
 webSocketClose(ws,code){ws.close(code);}
 webSocketError(ws){ws.close(1011,'Reconnect');}
}
export default {async fetch(request,env){const url=new URL(request.url),path=url.pathname,origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return json({error:'Origin rejected'},403);
 if(path==='/health')return json({ok:true,service:'maxi-agent-office',version:'0.2.0'});
 if(path==='/api/login'&&request.method==='POST'){const text=await request.text();if(text.length>2048)return json({error:'Invalid login'},400);let token;try{token=JSON.parse(text).token;}catch{}if(!env.VIEWER_TOKEN||token!==env.VIEWER_TOKEN)return json({error:'Access denied'},401);return json({ok:true},200,{'set-cookie':`office=${env.VIEWER_TOKEN}; Secure; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400`});}
 if(path==='/api/sync'&&request.method==='POST'){if(!env.PRODUCER_TOKEN||request.headers.get('Authorization')!==`Bearer ${env.PRODUCER_TOKEN}`)return json({error:'Access denied'},401);return env.ROOM.getByName('office').fetch(request);}
 if(path.startsWith('/api/')){const cookie=(request.headers.get('Cookie')||'').split('; ').find(x=>x.startsWith('office='))?.slice(7);if(!env.VIEWER_TOKEN||cookie!==env.VIEWER_TOKEN)return json({error:'Buka launcher pribadi untuk live'},401);if(['/api/snapshot','/api/ws'].includes(path)&&request.method==='GET')return env.ROOM.getByName('office').fetch(request);if(path==='/api/profile')return json({error:'Edit tampilan di collector lokal, lalu sinkronkan'},409);return json({error:'Unknown route'},404);}
 const asset=STATIC[path==='/'?'/index.html':path];if(!asset||request.method!=='GET')return json({error:'Not found'},404);return new Response(asset.base64?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body,{headers:{...headers,'content-type':asset.type}});
}};
